### ISSUE TITLE
Let phylostratr read blast outputs directly!

### ISSUE THREAD

**Issue by urmi-21** [arendsee/phylostratr#1]
Hi, It would be great if phylostratr can directly read blast output files. Currently, it still needs to run strata_blast() which is not necessary once we have the blast outputs already. This will also be helpful when one wants to run phylostratr multiple times using different thresholds.

**Comment by arendsee** [comment]
@urmi-21 Thanks, this is a good idea. One tricky issue is that `phylostratr` needs to figure out what the columns are. If the user is providing the files, they will need to either add headers to the files (which is a bit of a pain) or tell phylostratr, in an argument. I'm inclined towards the latter, since I don't want to add a manual step outside of R.

So I am thinking of a function something like this:

```R
strata <- load_blast(
  strata,
  files=c('3702' = 'at.tab', '9606' = 'human.tab'),
  fields=c('qseqid', 'sseqid', 'score')
)
```

This would load the BLAST files 'at.tab' and 'human.tab' into the `Strata` object, and assign the results to the species '3702' and '9606' (taxonomy IDs). The function would assume the BLAST files have no headers, loading them each as a `data.frame`. Then check to ensure the `fields` argument is compatible with the loaded table. Then set the `data.frame` column names to the fields. Then I might save the each `data.frame` as R data and save the filenames in the `Strata` object.

I'll get this function together soon, if I don't do it in a few days, you can ping me.

**Comment by urmi-21** [comment]
That would work. Another case is when all blast results are named according to the tax Ids i.e. 3702.tab, 9606.tab etc. In this case phylostratr can just read all these files from a path and add them to the corresponding strata object. If some file are missing it should report that too. This will be helpful in importing a large number of blast results and not providing file names as arguments.

**Comment by arendsee** [comment]
@urmi-21 Yeah, maybe I could allow the `files` argument to optionally take a single directory instead, and then try to guess which files in the directory are BLAST results and what their species is.

**Comment by arendsee** [comment]
OK @urmi-21 ! After almost a year I finally got around to implementing a function to read directly from BLAST directories. So now you can do this:

```R
strata_from_blast_dir('3702', 'my-blast-directory')
```

I also added a function to build a `Strata` object from a list of taxonomy IDs: `strata_from_taxids`.

**Comment by billadelonge** [comment]
Hi, I'm trying to use the function strata_from_blast_dir but I get the following error 
`Error in x$id : $ operator is invalid for atomic vectors`
